Formularze roznowicz zuzanna
rudnickirobert/KWZP2020 pull request #11
Opened 2020-05-04 19:15 UTC by zuzannaroznowicz

Pierwszy push grupa zarządzanie

2020-05-05 07:28 UTC, rudnickirobert requested changes

2020-05-05 07:28 UTC, rudnickirobert commented on Szwalnia/Start.cs
> +        private void Start_Load(object sender, EventArgs e)
do usunięcia

2020-05-05 07:28 UTC, rudnickirobert commented on Szwalnia/Start.cs
> +            ZarzadzanieForm zarzForm = new ZarzadzanieForm(szwalnia);
co to `zarz`?

2020-05-05 07:28 UTC, rudnickirobert commented on szwalnia/Klienci_szczegoly.cs
> +    public partial class Klienci_szczegoly : Form
PascalCase

2020-05-05 07:28 UTC, rudnickirobert commented on szwalnia/Klienci_szczegoly.cs
> +            Klienci employee = db.Klienci
na pewno `employee`?

2020-05-05 07:28 UTC, rudnickirobert commented on szwalnia/Klienci_szczegoly.cs
> +        public Klienci_szczegoly( SzwalniaEntities db, String employeeNazwaFirmy)
proszę się zdecydować na język polski lub angielski

2020-05-05 07:28 UTC, rudnickirobert commented on szwalnia/Start.cs
> +        private void Start_Load(object sender, EventArgs e)
do usuniecia

2020-05-05 07:28 UTC, rudnickirobert commented on szwalnia/Start.cs
> +            MagazynForm magForm = new MagazynForm(szwalnia);
po co skrót?

2020-05-05 07:28 UTC, rudnickirobert commented on szwalnia/Start.cs
> +            ZarzadzanieForm zarzForm = new ZarzadzanieForm(szwalnia);
po co skrót?

2020-05-05 07:28 UTC, rudnickirobert commented on szwalnia/Wybor_klienta.cs
> +            Klienci_szczegoly klienci_Szczegoly = new Klienci_szczegoly(db, txtNazwaFirmy.Text);
zmienna camelCase

2020-05-05 07:28 UTC, rudnickirobert commented on szwalnia/Wybor_klienta.cs
> +    public partial class Wybor_klienta : Form
PascalCase

2020-05-05 07:28 UTC, rudnickirobert commented on szwalnia/ZarzadzanieForm.cs
> +        private void ZarzadzanieForm_Load(object sender, EventArgs e)
do usuniecia

2020-05-05 08:05 UTC, zuzannaroznowicz commented on szwalnia/Start.cs
> +            MagazynForm magForm = new MagazynForm(szwalnia);
to jest część grupy magazynowej

2020-05-05 09:45 UTC, rudnickirobert requested changes
nie wszystkie uwagi są poprawione, proszę rozwiązać konflikty

2020-05-05 12:35 UTC, rudnickirobert requested changes

2020-05-05 12:35 UTC, rudnickirobert commented on Szwalnia/Faktury Zewnetrzne.cs
> +    public partial class Faktury_Zewnetrzne : Form
PascalCase

2020-05-05 12:35 UTC, rudnickirobert commented on Szwalnia/Faktury Zewnetrzne.cs
> +        private void label1_Click(object sender, EventArgs e)
do usunięcia

2020-05-05 12:35 UTC, rudnickirobert commented on szwalnia/Start.cs
> +            MagazynForm magForm = new MagazynForm(szwalnia);
ale to Pani dodała ten kod

2020-05-05 12:35 UTC, rudnickirobert commented
konflikty

2020-05-05 16:20 UTC, zuzannaroznowicz commented on Szwalnia/Faktury Zewnetrzne.cs
> +    public partial class Faktury_Zewnetrzne : Form
usunięty został cały formularz ponieważ zawierał liczne błędy i nie działał.

2020-05-05 16:20 UTC, zuzannaroznowicz commented on Szwalnia/Faktury Zewnetrzne.cs
> +        private void label1_Click(object sender, EventArgs e)
usunięty został cały formularz ponieważ zawierał liczne błędy i nie działał.

2020-05-05 16:21 UTC, zuzannaroznowicz commented on szwalnia/Wybor_klienta.cs
> +    public partial class Wybor_klienta : Form
poprawione na WyborKlienta

2020-05-05 16:21 UTC, zuzannaroznowicz commented on szwalnia/Wybor_klienta.cs
> +            Klienci_szczegoly klienci_Szczegoly = new Klienci_szczegoly(db, txtNazwaFirmy.Text);
poprawiono na KlienciSzczegoly oraz klienciSzczegoly

2020-05-05 16:21 UTC, zuzannaroznowicz commented on szwalnia/Start.cs
> +            ZarzadzanieForm zarzForm = new ZarzadzanieForm(szwalnia);
został zmieniony na zarzadzanieForm

2020-05-05 16:21 UTC, zuzannaroznowicz commented on szwalnia/Start.cs
> +            MagazynForm magForm = new MagazynForm(szwalnia);
poprawione

2020-05-05 16:22 UTC, zuzannaroznowicz commented on szwalnia/Klienci_szczegoly.cs
> +            Klienci employee = db.Klienci
nie, błąd kopiowania - zmienione na customer

2020-05-05 16:23 UTC, zuzannaroznowicz commented on szwalnia/Klienci_szczegoly.cs
> +    public partial class Klienci_szczegoly : Form
poprawione - KlienciSzczegoly

2020-05-05 16:23 UTC, zuzannaroznowicz commented on Szwalnia/Start.cs
> +            ZarzadzanieForm zarzForm = new ZarzadzanieForm(szwalnia);
poprawione zarzadzanieForm

2020-05-05 16:23 UTC, zuzannaroznowicz commented on Szwalnia/Start.cs
> +        private void Start_Load(object sender, EventArgs e)
usuniete

2020-05-05 16:40 UTC, rudnickirobert requested changes

2020-05-05 16:40 UTC, rudnickirobert commented on szwalnia/Start.cs
> +        private void btnPrzygotowanieProdukcji_Click(object sender, EventArgs e)
do usunięcia

2020-05-05 16:40 UTC, rudnickirobert commented on Szwalnia/Start.cs
>          private void btnPrzygotowanieProdukcji_Click(object sender, EventArgs e)
teraz metoda jest pusta -> do usunięcia

2020-05-05 16:40 UTC, rudnickirobert commented on szwalnia/WyborKlienta.cs
> +            int numID = Convert.ToInt32(dgvListaKlientow.CurrentRow.Cells[0].Value);
numId? przydałoby się nazwać za co odpowiedzialna jest ta zmienna

2020-05-05 16:46 UTC, zuzannaroznowicz commented on szwalnia/WyborKlienta.cs
> +            int numID = Convert.ToInt32(dgvListaKlientow.CurrentRow.Cells[0].Value);
poprawione na numIDKlienta

2020-05-05 16:46 UTC, zuzannaroznowicz commented on szwalnia/WyborKlienta.cs
> +            int numID = Convert.ToInt32(dgvListaKlientow.CurrentRow.Cells[0].Value);
numerIDKlienta *

2020-05-05 16:46 UTC, zuzannaroznowicz commented on Szwalnia/Start.cs
>          private void btnPrzygotowanieProdukcji_Click(object sender, EventArgs e)
usunięto

2020-05-06 12:11 UTC, zuzannaroznowicz commented on szwalnia/Start.cs
> +        private void btnPrzygotowanieProdukcji_Click(object sender, EventArgs e)
usunięto

2020-05-06 19:00 UTC, zuzannaroznowicz commented
konflikty rozwiazane

2020-05-06 19:29 UTC, zuzannaroznowicz commented
NIE MERGOWAC !!!!!!! problem z VisualStudio

2020-05-06 19:49 UTC, zuzannaroznowicz commented
Konflikty rozwiązane

2020-05-07 06:15 UTC, rudnickirobert approved these changes

2020-05-07 06:15 UTC, rudnickirobert commented on Szwalnia/FakturyZewnetrzneSzczegoly.cs
> +            //Faktury_Zewnetrzne faktura = db.Faktury_Zewnetrzne.Where(wybrane => wybrane.ID_Faktura_zewnetrzna == ID).First();
nie commitujemy zakomentowanego kodu

2020-05-07 06:15 UTC, merged