Magazyn module
rudnickirobert/KWZP2020 pull request #41
Opened 2020-05-13 12:51 UTC by zrider100z

Skeleton of magazyn module added. Please do not remove the branch after merge.

2020-05-13 13:19 UTC, zrider100z commented on Szwalnia/DodawanieCechy.cs
> +        public SzwalniaEntities db;
W tej wersji został dodany głównie szkielet. Część z formularzy posiada początki kodu wymaganego dla swojej funkcjonalności, ale nie zawsze są wykorzystywane. Przykład powyżej - deklaracja db.

2020-05-13 13:43 UTC, rudnickirobert requested changes

2020-05-13 13:43 UTC, rudnickirobert commented on Szwalnia/DodawanieCechy.cs
> +            db.Elementy_Cechy_Slownik.Add(cechaNew);
tutaj będzie wyjątek null pointer

2020-05-13 13:43 UTC, rudnickirobert commented on Szwalnia/DodawanieCechy.cs
> +            db.Elementy_Cechy_Slownik.Add(cechaNew);
brakuje również saveChanges

2020-05-13 13:43 UTC, rudnickirobert commented on Szwalnia/DodawanieElementu.cs
> +            dgvListaTypy.DataSource = db.Elementy_Typy.ToList();
db jest `null`em

2020-05-13 13:43 UTC, rudnickirobert commented on Szwalnia/DodawanieJednostki.cs
> +            db.Elementy_Jednostki.Add(jednostkaNew);
db jest `null`em

2020-05-13 13:43 UTC, rudnickirobert commented on Szwalnia/DodawanieCechy.cs
> +        public SzwalniaEntities db;
przejrzałem kilka plików, dalej nie przeglądam - proszę oznaczyć PR jako review required gdy kod będzie gotowy

2020-05-15 12:56 UTC, rudnickirobert requested changes

2020-05-15 12:56 UTC, rudnickirobert commented on Szwalnia/NowyRegal.cs
> +            if (b == true)
1. zmienna powinna mieć nazwę 
2. zmienna jest niepotrzebna :) wystarczy: `if (isUnique())`

2020-05-15 12:56 UTC, rudnickirobert commented on Szwalnia/NowyRegal.cs
> +        private bool unique()
proponuję nazwę `isUniqe`

2020-05-15 12:56 UTC, rudnickirobert commented on Szwalnia/NowyRegal.cs
> +            string nowy = txtOznaczenie.Text;
niepotrzebna zmienna, `txtOznaczenie.Text` mozna wywołać bezpośrednio w 57 linii

2020-05-15 14:25 UTC, rudnickirobert submitted a review, later dismissed

2020-05-15 14:25 UTC, rudnickirobert commented on Szwalnia/DodawanieTypu.cs
> +            { typNew.Czy_wlasne = true; }
formatowanie

2020-05-15 14:25 UTC, rudnickirobert commented on Szwalnia/DodawanieTypu.cs
> +            { typNew.Czy_wlasne = true; }
`typNew.Czy_wlasne = chBoxWlasny.Checked`

2020-05-15 22:36 UTC, rudnickirobert approved these changes

2020-05-15 22:36 UTC, merged